name: foundpose_gpu
channels:
  - defaults
  - pytorch
  - nvidia
  - xformers
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.0
  - cython=3.0.12
  - faiss-gpu=1.8.0 # GPU
  - pip:
    - torch==2.3.0
    - torchvision==0.18.0
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - omegaconf
    - torchmetrics==0.10.3
    - fvcore
    - iopath
    - torchinfo
    - omegaconf
    - scipy==1.13.0
    - kiwisolver==1.3.1
    - matplotlib==3.8.4
    - numpy==1.26.4
    - pillow==10.3.0
    - vispy==0.12.1
    - xformers==0.0.26.post1 # GPU
    - git+https://github.com/facebookincubator/submitit
    - --extra-index-url https://pypi.nvidia.com
    - cuml-cu11==23.04 # GPU
    - --extra-index-url https://pypi.nvidia.com
    - kornia==0.7.2
    - pypng==0.20220715.0
    - triangle==20250106
    - glumpy==1.2.1
    - pycocotools==2.0
    - scikit-learn==1.5.0
    - scikit-image==0.22.0
    - imageio==2.34.1
    - pyopengl==3.1.0
    - pyglet==2.0.15
    - pytz==2024.1
    - pyrender==0.1.45
    - webdataset==0.2.86
    - git+https://github.com/facebookresearch/hand_tracking_toolkit
    - opencv-python==4.5.5.62
